### ISSUE TITLE
Sounds strange when sampling rate is set to 48000 Hz

### ISSUE THREAD

**Issue by 4vv2** [tesserato/PianoForte#1]
Here is my environment:
- OS: Windows 11 Pro 64bit 10.0.22621
- Software: Studio One 6 Artist 6.1.2.93766
- ASIO: JackAudio in 48000Hz, 128 sample/buffer

Sounds strange when sampling rate is set to 48000 Hz like a attachment in this post.
Perhaps the sampling rate is included in a constant in the program, and the processing that depends on it is causing the problem.

https://github.com/tesserato/PianoForte/assets/38828702/89e95070-caaf-4d28-a52c-aad2920bafb1

**Comment by tesserato** [comment]
I'll take a look into it. Sample rates are not hardcoded, but have a default value of 44100 Hz. They are supposed to be updated before each note begins, so I'm betting the problem is in the process of getting this value from Studio One.

**Comment by zopty** [comment]
It works. Thank you!
